apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "..fullname" . }}-api-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
