apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scale-app-ui-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scale-app
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: scale-app
