{{- if .Values.certManager.issuer.create }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretsManager.name }}
  namespace: {{ .Values.secretsManager.namespace }}
spec:
  provider:
    aws:
      service: {{ .Values.secretsManager.service }}
      region: {{ .Values.secretsManager.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.esoserviceAccount.name }}
{{- end }}