apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-service-ui
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
    - port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
