apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-service-ui
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "..labels" . | nindent 4 }}
spec:
  selector:
{{- include "..uiSelectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
