apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" $ }}-service-api
spec:
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
