apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}-service
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "..name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - port: 8000
      targetPort: 8000
  type: {{ .Values.service.type }}
