apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.fullname" . }}-service
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
      targetPort: 8000
  type: {{ .Values.service.type }}
