apiVersion: v1
kind: Service
metadata:
  name: scale-app-ui-service
  labels:
    app.kubernetes.io/name: scale-app
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: scale-app
spec:
  selector:
    app.kubernetes.io/name: scale-app
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: scale-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}