apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" $ }}-service-ui
spec:
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
