{{- if .Values.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
spec:
  acme:
    server: {{ .Values.certManager.issuer.server }}
    email: {{ .Values.certManager.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuer.privateKeySecretName }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
